config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :billet_settings, only: [:show, :edit, :update]
    get 'billet_settings/clear_shipping', to: 'billet_settings#clear_shipping', as: :clear_shipping

    get  'billets/shipping',    to: 'billets#shipping',    as: :billets_shipping
    get  'billets/return',      to: 'billets#return',      as: :billets_return
    post 'billets/register',    to: 'billets#register',    as: :billets_register
    post 'billets/return_info', to: 'billets#return_info', as: :billets_return_info
  end

  resources :billets, only: [:show]
end

app/views/spree/admin/payments/source_views/_billet.html.erb
<fieldset data-hook="billet">
  <legend>
    <%= Spree.t(:billet) %>
  </legend>
  <table class="table table-condensed table-bordered">
    <tr>
      <th><%= Spree.t(:number) %>:</th>
      <td><%= payment.source.document_number %>
    </tr>
    <tr>
      <th><%= Spree.t(:amount) %>:</th>
      <td><%= payment.source.display_amount.to_html %>
    </tr>
    <tr>
      <th><%= Spree.t(:due_date) %>:</th>
      <td><%= payment.source.due_date.strftime(t('date.formats.default')) %>
    </tr>
    <% if payment.source.paid? %>
      <tr>
        <th><%= Spree.t(:paid_in) %>:</th>
        <td><%= payment.source.paid_in.strftime(t('date.formats.default')) rescue '' %>
      </tr>
    <% end %>
    <tr>
      <th><%= Spree.t(:status) %>:</th>
      <td>
        <label class="label label-<%= payment.source.status %>"><%= Spree.t(payment.source.status) %></label>
      </td>
    </tr>
    <% if payment.source.can_generate_document? %>
      <tr>
        <td colspan="2">
          <%= link_to Spree.t(:generate_billet), billet_path(payment.source_id),
                      target: '_blank', class: 'btn btn-sm btn-info pull-right' %>
        </td>
      </tr>
    <% end %>
  </table>
</fieldset>