config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :billet_settings, only: [:show, :edit, :update]
    get 'billet_settings/clear_shipping', to: 'billet_settings#clear_shipping', as: :clear_shipping

    get  'billets/shipping',    to: 'billets#shipping',    as: :billets_shipping
    get  'billets/return',      to: 'billets#return',      as: :billets_return
    post 'billets/register',    to: 'billets#register',    as: :billets_register
    post 'billets/return_info', to: 'billets#return_info', as: :billets_return_info
  end

  resources :billets, only: [:show]
end

app/models/spree/billet.rb
module Spree
  class Billet < ActiveRecord::Base

    has_one :payment, as: :source
    belongs_to :order
    belongs_to :user
    belongs_to :payment_method

    scope :unregistered, -> { where(status: 'waiting_registry') }

    # Displays what actions can be done according to payment method
    #
    # @author Isabella Santos
    #
    # @return [Array]
    #
    def actions
      act = []
      act << 'capture' if can_capture? payment
      act << 'void' if can_void? payment
      act
    end

    # Save the amount of the billet
    # if amount is a string, convert to a BigDecimal
    #
    # copy of Spree::Payment.amount
    #
    def amount=(amount)
      self[:amount] =
          case amount
            when String
              separator = I18n.t('number.currency.format.separator')
              number    = amount.delete("^0-9-#{separator}\.").tr(separator, '.')
              number.to_d if number.present?
          end || amount
    end

    # Determines whether can capture the payment
    # (only can capture when the state is checkout or pending)
    #
    # @author Isabella Santos
    #
    # @return [Boolean]
    #
    def can_capture?(payment)
      payment.pending? || payment.checkout?
    end

    # Determines whether can void the payment
    # (only can void when the state is different of void, failure or invalid)
    #
    # @author Isabella Santos
    #
    # @return [Boolean]
    #
    def can_void?(payment)
      !%w(void failure invalid).include?(payment.state)
    end

    # Defines the currency of the billet
    # based in te currency of the order
    #
    # copy of Spree::Payment.currency
    #
    def currency
      order.currency
    end

    # Calculates the due date
    # according to created at
    #
    # @author Isabella Santos
    #
    # @return [Date]
    #
    def due_date
      created_at + Spree::BilletConfig.due_date.days
    end

    # Generate the object from gem brcobranca
    #
    # @author Isabella Santos
    #
    # @return [Brcobranca::Boleto::Base]
    #
    def generate_document
      config = Spree::BilletConfig
      doc_user = user.attributes[config.doc_customer_attr] rescue ''
      due_date = Date.today + config.due_date.days

      params = {cedente: config.corporate_name,
                documento_cedente: config.document,
                cedente_endereco: config.address,
                sacado: self.customer_name,
                sacado_documento: doc_user,
                sacado_endereco: order.bill_address.full_address,
                numero_documento: document_number,
                data_vencimento: due_date,
                data_documento: Date.parse(created_at.to_s),
                valor: amount,
                aceite: config.acceptance,
                agencia: config.agency,
                conta_corrente: config.account,
                convenio: config.agreement,
                carteira: config.wallet,
                variacao: config.variation_wallet
      }
      (1..6).each { |cont| params["instrucao#{cont}".to_sym] = config["instruction_#{cont}"] }
      if config.bank == 'sicredi' then
        params.merge!({posto: config.office_code,
                       byte_idt: config.byte_idt})
      end

      document = case config.bank
                   when 'banco_brasil' then Brcobranca::Boleto::BancoBrasil.new params
                   when 'bradesco'     then Brcobranca::Boleto::Bradesco.new params
                   when 'caixa'        then Brcobranca::Boleto::Caixa.new params
                   when 'santander'    then Brcobranca::Boleto::Santander.new params
                   when 'itau'         then Brcobranca::Boleto::Itau.new params
                   when 'sicredi'      then Brcobranca::Boleto::Sicredi.new params
                   else
                  raise 'It is necessary set the billet config'
                 end
      document
    end

    # Return the amount converted to Money
    # according to currency
    #
    # copy of Spree::Payment.money
    #
    def money
      Spree::Money.new(amount, { currency: currency })
    end
    alias display_amount money

    # Returns the name of the customer according
    # to bill address of order
    #
    # @author Isabella Santos
    #
    # @return [String]
    #
    def customer_name
      "#{order.bill_address.firstname} #{order.bill_address.lastname}"
    rescue
      ''
    end

    # Returns if billet is paid
    #
    # @author Isabella Santos
    #
    # @return [Boolean]
    #
    def paid?
      status == 'paid'
    end

    # Returns if billet is pending
    #
    # @author Isabella Santos
    #
    # @return [Boolean]
    #
    def pending?
      status == 'pending'
    end

    # Returns if billet is waiting registry
    #
    # @author Isabella Santos
    #
    # @return [Boolean]
    #
    def waiting_registry?
      status == 'waiting_registry'
    end

    # Return if it is possible generate the document
    # (when status is waiting registry or pending)
    #
    # @author Isabella Santos
    #
    # @return [Boolean]
    #
    def can_generate_document?
      %w(waiting_registry pending).include?(status)
    end

    # Chanege the status to pending
    #
    # @author Isabella Santos
    #
    def to_pending!
      self.status = 'pending'
      self.save
    end

    def self.generate_shipping
      return {reason: :there_are_not_any_billets_to_registry, messages: []} if unregistered.empty?
      config = Spree::BilletConfig
      params = {empresa_mae: config.corporate_name,
                agencia: config.agency,
                conta_corrente: config.account,
                sequencial_remessa: config.shipping_number}
      document = case config.bank
                   when 'banco_brasil'
                     Brcobranca::Remessa::Cnab240::BancoBrasil.new(params.merge!({convenio: config.agreement,
                                                                                  carteira: config.wallet,
                                                                                  documento_cedente: config.document,
                                                                                  variacao: config.variation_wallet}))
                   when 'bradesco'
                     Brcobranca::Remessa::Cnab400::Bradesco.new(params.merge!({digito_conta: config.account_digit,
                                                                               carteira: config.wallet,
                                                                               codigo_empresa: config.company_code}))
                   when 'caixa'
                     Brcobranca::Remessa::Cnab240::Caixa.new(params.merge!({convenio: config.agreement,
                                                                            digito_conta: config.account_digit,
                                                                            documento_cedente: config.document,
                                                                            versao_aplicativo: config.app_version}))
                   when 'itau'
                     Brcobranca::Remessa::Cnab400::Itau.new(params.merge!({carteira: config.wallet,
                                                                           documento_cedente: config.document,
                                                                           digito_conta: config.account_digit}))
                   else
                     return {reason: :billet_bank_not_implemented, messages: []}
                 end
      document.pagamentos = []
      unregistered.each do |billet|
        next if billet.user.nil?
        doc_user = billet.user.attributes[config.doc_customer_attr] rescue ''
        user_address = billet.order.bill_address
        payment = Brcobranca::Remessa::Pagamento.new(valor: billet.amount,
                                                     data_vencimento: billet.due_date,
                                                     nosso_numero: billet.document_number,
                                                     documento_sacado: doc_user,
                                                     nome_sacado: billet.customer_name,
                                                     endereco_sacado: user_address.address1,
                                                     bairro_sacado: user_address.address2,
                                                     cep_sacado: user_address.zipcode,
                                                     cidade_sacado: user_address.city,
                                                     uf_sacado: user_address.state.abbr)
        document.pagamentos << payment
      end
      shipping = document.gera_arquivo
      if shipping.is_a? String
        config.shipping_number += 1
        # change the status of billets to pending
        unregistered.each { |billet| billet.to_pending! }
      end
      shipping
    rescue Brcobranca::RemessaInvalida => invalid
      {reason: :invalid_billets, messages: invalid.to_s.split(', ')}
    end
  end
end

app/models/spree/payment_method/billet.rb
module Spree
  class PaymentMethod::Billet < PaymentMethod

    def payment_source_class
      Spree::Billet
    end

    # Purchases the payment
    # saving the amount, document number (payment ID)
    # on source object (Spree::Billet)
    # This method is called when th payment method is set to auto capture
    # so, this will create the billet with status paid
    #
    # @author Isabella Santos
    #
    # @return [ActiveMerchant::Billing::Response]
    #
    def purchase(amount, source, *args)
      source.amount = amount.to_d / 100
      source.document_number = source.payment.id
      source.status = 'paid'

      source.payment.response_code = source.document_number
      ret = source.save

      ActiveMerchant::Billing::Response.new(ret, '', {}, authorization: source.document_number)
    end

    # Authorizes the payment
    # saving the amount, document number (payment ID)
    # on source object (Spree::Billet)
    #
    # @author Isabella Santos
    #
    # @return [ActiveMerchant::Billing::Response]
    #
    def authorize(amount, source, *args)
      source.amount = amount.to_d / 100
      source.document_number = source.payment.id

      ret = source.save

      ActiveMerchant::Billing::Response.new(ret, '', {}, authorization: source.document_number)
    end

    # Captures the payment
    # modifying the status and amount and saving the paid date
    # of the source (Spree::Billet)
    #
    # @author Isabella Santos
    #
    # @return [ActiveMerchant::Billing::Response]
    #
    def capture(amount, response_code, gateway_options)
      billet = Spree::Billet.find_by document_number: response_code
      billet.amount = amount.to_d / 100
      billet.paid_in = Date.today
      billet.status = 'paid'
      billet.save

      ActiveMerchant::Billing::Response.new(true, 'Billet Method: Successfully captured', {}, authorization: response_code)
    rescue
      ActiveMerchant::Billing::Response.new(false, 'Billet Method: Failed when try capture', {}, {})
    end

    # Voids the payment
    # modifying the status of the source (Spree::Billet)
    #
    # @author Isabella Santos
    #
    # @return [ActiveMerchant::Billing::Response]
    #
    def void(response_code, gateway_options)
      billet = Spree::Billet.find_by document_number: response_code
      billet.status = 'void'
      billet.save

      ActiveMerchant::Billing::Response.new(true, 'Billet Method: Successfully voided', {}, authorization: response_code)
    rescue
      ActiveMerchant::Billing::Response.new(false, 'Billet Method: Failed when try void', {}, {})
    end

    # Cancel the payment
    # modifying the status of the source (Spree::Billet)
    #
    # @author Isabella Santos
    #
    # @return [ActiveMerchant::Billing::Response]
    #
    def cancel(response_code)
      billet = Spree::Billet.find_by document_number: response_code
      billet.status = 'void'
      billet.save

      ActiveMerchant::Billing::Response.new(true, 'Billet Method: Successfully canceled', {}, authorization: response_code)
    rescue
      ActiveMerchant::Billing::Response.new(false, 'Billet Method: Failed when try cancel', {}, {})
    end
  end
end

app/controllers/spree/admin/billets_controller.rb
class Spree::Admin::BilletsController < Spree::Admin::BaseController

  def shipping
    @billets = Spree::Billet.unregistered
  end

  def register
    shipping = Spree::Billet.generate_shipping
    if shipping.is_a? String
      # formats the name of the file
      name = ''
      name << 'C' + Spree::BilletConfig.bank[0].upcase
      name << Date.today.day.to_s.rjust(2, '0')
      name << Date.today.month.to_s.rjust(2, '0')
      name << SecureRandom.hex(1).upcase
      name

      send_data shipping, :content_type => 'text/plain', :filename => "#{name}.rem"
    else
      flash[:error] = Spree.t("errors.#{shipping[:reason]}")
      redirect_to :admin_billets_shipping
    end
  end

  def return
  end

  def return_info
    data = case params[:file_type].to_sym
             when :cnab240 then Brcobranca::Retorno::RetornoCnab240.load_lines params[:file].path
             when :cnab400 then Brcobranca::Retorno::RetornoCnab400.load_lines params[:file].path
             when :cbr643  then Brcobranca::Retorno::RetornoCbr643.load_lines params[:file].path
           end

    @lines = []
    data.each do |line|
      # se for o registro trailer passa para a proxima iteracao
      next if line == data.last
      payment = Spree::Payment.find_by id: line.nosso_numero

      if payment and line.valor_recebido.to_i > 0 and !(payment.completed? or payment.void?)
        amount_paid = line.valor_recebido.to_f + line.valor_tarifa.to_f
        payment.capture! amount_paid

        # formats the date
        year = line.data_credito.size == 6 ? line.data_credito : "20#{line.data_credito}"
        paid_at = "#{year}#{line.data_credito[2..3]}#{line.data_credito[0..1]}".to_date
        # formats the value
        value = (line.valor_titulo.to_f / 100) + (line.valor_tarifa.to_f / 100)

        @lines.push({document_number: line.nosso_numero,
                     value: Spree::Money.new(value, { currency: payment.currency }),
                     paid_at: paid_at,
                     order_id: payment.order_id,
                     order_number: payment.order.number})
      end
    end
  rescue
    flash[:error] = Spree.t('errors.error_in_billets_return')
  end

  private

  def model_class
    Spree::BilletsController
  end

end

app/controllers/spree/billets_controller.rb
class Spree::BilletsController < Spree::StoreController

  before_action :load_data, only: :show

  def show
    if @billet.due_date.past?
      # voids the old payment
      old_payment = @billet.payment
      old_payment.void_transaction!

      # creates the new payment
      params = {order: @billet.order,
                amount: old_payment.amount,
                payment_method: @billet.payment_method,
                source_attributes: {order: @billet.order,
                                    user: @billet.user,
                                    status: 'pending'}}
      new_payment = Spree::Payment.new(params)
      new_payment.pend!
      new_payment.process!

      @billet = new_payment.source
    end
    # generate the billet document
    @document = @billet.generate_document
    send_data @document.to_pdf, filename: "boleto_#{@billet.order.number}.pdf"
  end

  private

  def load_data
    @billet = Spree::Billet.find params[:id] || params[:billet_id]
  end

end

app/views/spree/admin/billets/return.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/payment' %>

<% content_for :page_title do %>
    <%= Spree.t(:billet_return) %>
<% end %>

<%= form_for admin_billets_return_info_path, url: admin_billets_return_info_path, method: 'post', html: { multipart: true } do %>
    <div id="billets_return" data-hook="billets_return">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title">
            <%= Spree.t(:billet_return_info) %>
          </h1>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-6">
              <%= label_tag :file_type, Spree.t(:file_type) + ': ' %>
              <br />
              <%= radio_button_tag :file_type, :cnab240, false, required: true %>
              <%= label_tag :file_type_cnab240, Spree.t(:cnab240) %>
              <br />
              <%= radio_button_tag :file_type, :cnab400, false, required: true %>
              <%= label_tag :file_type_cnab400, Spree.t(:cnab400) %>
              <br />
              <%= radio_button_tag :file_type, :crb643, false, required: true %>
              <%= label_tag :file_type_crb643, Spree.t(:CBR643) %>
            </div>
            <div class="col-xs-6">
              <%= label_tag :file, Spree.t(:file) %>
              <%= file_field_tag :file, required: true %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.continue'), 'ok', 'submit', {class: 'btn-success'} %>
    </div>
<% end %>

app/views/spree/admin/billets/return_info.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/payment' %>

<% content_for :page_title do %>
    <%= Spree.t(:billet_return) %>
<% end %>

<% if @lines.present? %>
    <table class="table" id="listing_returned_billets" data-hook="listing_returned_billets">
      <thead>
      <tr data-hook="admin_returned_billets_headers">
        <th><%= Spree.t(:document_number) %></th>
        <th><%= Spree.t(:value) %></th>
        <th><%= Spree.t(:paid_at) %></th>
        <th><%= Spree.t(:order) %></th>
      </tr>
      </thead>
      <tbody>
      <% @lines.each do |line| %>
          <tr data-hook="admin_returned_billets_rows" class="<%= cycle('odd', 'even') %>">
            <td><%= link_to line[:document_number], spree.admin_order_payment_path(line[:order_id], line[:document_number]) %></td>
            <td><%= line[:value].to_html %></td>
            <td><%= line[:paid_at].strftime(t('date.formats.default')) %></td>
            <td><%= link_to line[:order_number], spree.edit_admin_order_path(line[:order_id]) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:there_is_not_return_in_file) %>
    </div>
<% end %>

app/views/spree/admin/billets/shipping.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/payment' %>

<% content_for :page_title do %>
    <%= Spree.t(:billet_shipping) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:register_billets), spree.admin_billets_register_path, class: 'btn-success', icon: 'download-alt',
                                                                                      id: 'register_billets', method: 'post' %>
<% end if @billets.present? %>

<% if @billets.present? %>
    <table class="table" id="listing_unregistered_billets" data-hook="listing_unregistered_billets">
      <thead>
      <tr data-hook="admin_billets_register_headers">
        <th><%= Spree.t(:document_number) %></th>
        <th><%= Spree.t(:customer) %></th>
        <th><%= Spree.t(:amount) %></th>
        <th><%= Spree.t(:created_at) %></th>
        <th><%= Spree.t(:due_date) %></th>
      </tr>
      </thead>
      <tbody>
      <% @billets.each do |billet| %>
          <tr data-hook="admin_billets_register_rows" class="<%= cycle('odd', 'even') %>">
            <td><%= link_to billet.document_number, spree.admin_order_payment_path(billet.order_id, billet.payment.id) %></td>
            <td><%= billet.customer_name %></td>
            <td><%= billet.display_amount.to_html %></td>
            <td><%= billet.created_at.strftime(t('date.formats.default')) %></td>
            <td><%= billet.due_date.strftime(t('date.formats.default')) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Billet)) %>
    </div>
<% end %>